"""Initial database

Revision ID: 38bca5a9d107
Revises: 
Create Date: 2021-10-09 10:45:46.595848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bca5a9d107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmi_troqueladora_73',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funcionando', sa.Boolean(), nullable=False),
    sa.Column('parada', sa.Boolean(), nullable=False),
    sa.Column('numero_piezas', sa.Integer(), nullable=True),
    sa.Column('produccion_estimada', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hmi_troqueladora_73')
    # ### end Alembic commands ###
