"""Initial database

Revision ID: 400b9366a882
Revises: 8e220a84a292
Create Date: 2021-10-09 15:06:06.005825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400b9366a882'
down_revision = '8e220a84a292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hmi_troqueladora_73', sa.Column('referencia_3', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hmi_troqueladora_73', 'referencia_3')
    # ### end Alembic commands ###
