"""Initial database

Revision ID: 8e220a84a292
Revises: 
Create Date: 2021-10-09 15:04:12.890562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e220a84a292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmi_troqueladora_73',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funcionando', sa.Boolean(), nullable=False),
    sa.Column('parada', sa.Boolean(), nullable=False),
    sa.Column('referencia_1', sa.Boolean(), nullable=False),
    sa.Column('referencia_2', sa.Boolean(), nullable=False),
    sa.Column('numero_piezas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hmi_troqueladora_73')
    # ### end Alembic commands ###
