"""Initial database

Revision ID: d7ce54df0483
Revises: 
Create Date: 2021-10-20 17:13:05.971161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ce54df0483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmi_troqueladora_73',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datee', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onn', sa.Boolean(), nullable=True),
    sa.Column('reference_1', sa.Integer(), nullable=True),
    sa.Column('number_pieces', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hmi_troqueladora_74',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datee', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onn', sa.Boolean(), nullable=True),
    sa.Column('reference_1', sa.Integer(), nullable=True),
    sa.Column('number_pieces', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hmi_troqueladora_74')
    op.drop_table('hmi_troqueladora_73')
    # ### end Alembic commands ###
